name: 自动构建
on:
  workflow_dispatch:
jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: 检出当前仓库
        uses: actions/checkout@v3
      - name: 准备Release变量
        run: |
          sed '/^$/d' .release | uniq | awk -F '=' '{print " " $1 "=" $2}' | while read line; do
            export $line
          done
          echo "======> Release变量准备完毕"
      - name: 生成规则文件
        run: |
          templates_rule_file="resources/${VERSION}/templates.yml"
          if [ -f "${templates_rule_file}" ]; then
            echo "======> 规则文件已经存在"
            exit
          fi
          apt-get update
          apt-get install gettext
          envsubst < src/templates-replace/rule.tpl.yml > ${templates_rule_file}
          echo "======> 规则文件生成完毕"





