name: 自动构建
on:
  workflow_dispatch:
jobs:
  main-job:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
    steps:
      - name: 检出当前仓库
        uses: actions/checkout@v3
      - name: 准备Git环境
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: 准备Release变量
        run: |
          set -a
          source .release.env
          set +a
          cat .release.env >> $GITHUB_ENV
          
          VERSION_DIR=resources/${VERSION}
          echo "VERSION_DIR=${VERSION_DIR}" >> $GITHUB_ENV
          mkdir -p ${VERSION_DIR}

          TEMPLATES_DIR=${VERSION_DIR}/templates
          echo "TEMPLATES_DIR=${TEMPLATES_DIR}" >> $GITHUB_ENV
          if [ -d "${TEMPLATES_DIR}" ]; then
            echo "TEMPLATES_DIR_EXIST=true" >> $GITHUB_ENV
            echo "======> 资源目录已经存在"
          fi

          RULE_PATH=${VERSION_DIR}/templates.yml
          echo "RULE_PATH=${RULE_PATH}" >> $GITHUB_ENV
          if [ -f "${RULE_PATH}" ]; then
            echo "RULE_PATH_EXIST=true" >> $GITHUB_ENV
            echo "======> 规则文件已经存在"
          fi

          LINKDING_TEMP_DIR=/tmp/$(uuidgen)/linkding
          echo "LINKDING_TEMP_DIR=${LINKDING_TEMP_DIR}" >> $GITHUB_ENV
          mkdir -p ${LINKDING_TEMP_DIR}

          LINKDING_RELEASE_ZIP_URL=https://github.com/sissbruecker/linkding/archive/refs/tags/v${VERSION}.zip
          echo "LINKDING_RELEASE_ZIP_URL=${LINKDING_RELEASE_ZIP_URL}" >> $GITHUB_ENV

          FROM_IMAGE_TAG=sissbruecker/linkding:${VERSION}
          echo "FROM_IMAGE_TAG=${FROM_IMAGE_TAG}" >> $GITHUB_ENV

          BUILD_IMAGE_TAG=${{ secrets.DOCKER_HUB_USERNAME }}/linkding-cn:${VERSION}
          echo "BUILD_IMAGE_TAG=${BUILD_IMAGE_TAG}" >> $GITHUB_ENV

          BUILD_IMAGE_TAG_LATEST=${{ secrets.DOCKER_HUB_USERNAME }}/linkding-cn:latest
          echo "BUILD_IMAGE_TAG_LATEST=${BUILD_IMAGE_TAG_LATEST}" >> $GITHUB_ENV

          echo "======> Release变量准备完毕"
      - name: 生成规则文件
        if: env.RULE_PATH_EXIST != 'true'
        run: |
          #sudo apt-get update
          #sudo apt-get install gettext
          mkdir -p ${VERSION_DIR}
          envsubst < src/templates-replace/rule.tpl.yml > ${RULE_PATH}
          git add .
          git commit -m "生成规则文件"
          git push
          echo "======> 规则文件生成完毕"
      - name: 设置 JRE 运行环境
        if: env.TEMPLATES_DIR_EXIST != 'true'
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 8
      - name: 下载 Linkding 原始资源
        if: env.TEMPLATES_DIR_EXIST != 'true'
        run: |
          zip_file=${LINKDING_TEMP_DIR}/linkding-${VERSION}.zip
          wget ${LINKDING_RELEASE_ZIP_URL} -O ${zip_file}
          unzip ${zip_file} -d ${LINKDING_TEMP_DIR}
          echo "======> Linkding 原始资源下载并解压完毕"
      - name: 生成模板文件
        if: env.TEMPLATES_DIR_EXIST != 'true'
        run: |
          java -jar tools/text-replace/text-replace.jar -i ${LINKDING_TEMP_DIR}/linkding-${VERSION}/bookmarks/templates -o ${TEMPLATES_DIR} -r ${RULE_PATH}
          git add .
          git commit -m "生成模板文件"
          git push
          echo "======> 模板文件生成完毕"
      - name: 构建 Docker 镜像
        run: |
          echo "
          FROM ${FROM_IMAGE_TAG}
          COPY resources/${VERSION}/templates /etc/linkding/bookmarks/
          CMD ["./bootstrap.sh"]
          " > Dockerfile
          docker build -t ${BUILD_IMAGE_TAG} .
          rm -rf Dockerfile
          echo "======> Docker 镜像构建完毕"
          docker images
      - name: 上传镜像到 Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker push ${BUILD_IMAGE_TAG}
          if [ ${LATEST} -eq "true" ]; then
            docker tag ${BUILD_IMAGE_TAG} ${BUILD_IMAGE_TAG_LATEST}
            docker push ${BUILD_IMAGE_TAG_LATEST}
          fi
          echo "======> Docker 镜像上传完毕"
          docker logout






