name: 自动构建
on:
  workflow_dispatch:
jobs:
  main-job:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
    steps:
      - name: 检出当前仓库
        uses: actions/checkout@v3
      - name: 准备Git环境
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: 准备Release变量
        run: |
          cat .release.env >> $GITHUB_ENV
          echo "======> Release变量准备完毕"
      - name: 生成规则文件
        run: |
          echo 1111111111:${VERSION}
          templates_rule_file="resources/${VERSION}/templates.yml"
          if [ -f "${templates_rule_file}" ]; then
            echo "======> 规则文件已经存在"
            exit
          fi
          #sudo apt-get update
          #sudo apt-get install gettext
          envsubst < src/templates-replace/rule.tpl.yml > ${templates_rule_file}
          git add .
          git commit -m "生成规则文件"
          git push
          echo "======> 规则文件生成完毕"





